################################################################################
#
#  Makefile for the NCAR PyReshaper Benchmark Tests - ./Tests/
#
# COPYRIGHT 2017, University Corporation for Atmospheric Research
################################################################################

test:
    @if [ "$$GENARGS" = "" ]; then exit 1; fi
    @if [ "$$GENLOG" = "" ]; then exit 1; fi
    @if [ "$$RUNARGS" = "" ]; then exit 1; fi
    @if [ "$$RUNLOG" = "" ]; then exit 1; fi

	@echo "Running benchmark: $@"
	@echo "  Generating input data."
	@$(ACTIVATE) && $(MPIRUN) $(GENDATA) $$GENARGS > $$GENLOG
	@if [ ! -d output ]; then mkdir output; fi
	@echo "  Running test."
	@$(ACTIVATE) && $(MPIRUN) $(EXECRUN) $$RUNARGS > $$RUNLOG
	@$(ACTIVATE) && $(CHECK) -p "$@." $$GENARGS
	@$(ACTIVATE) && $(POST) -l $$RUNLOG
	@echo "  Copying logfiles."
	@cp *.log $(PREFIX)/logs/
	@echo "  Done."
	@echo

$(tests): logdir
	@$(MAKE) -C $@
